// Inventario editable de TCG Cards. Precios expresados en la moneda indicada.
window.TCG_INVENTORY = [
  { id: 1, name: "Charizard ex — Ilustración Especial", category: "singles", price: 2899, currency: "MXN", status: "available", image_url: "", description: "Una pieza central para cualquier carpeta de coleccionista.", is_holo: true, set_name: "151", card_number: "199/165" },
  { id: 2, name: "Pikachu — Rareza Secreta", category: "singles", price: 1249, currency: "MXN", status: "available", image_url: "", description: "Arte vibrante y acabado holográfico premium.", is_holo: true, set_name: "Corona Astral", card_number: "160/159" },
  { id: 3, name: "Umbreon VMAX", category: "singles", price: 899, currency: "MXN", status: "sold_out", image_url: "", description: "Una evolución oscura con brillo espectacular.", is_holo: true, set_name: "Cielos Evolutivos", card_number: "095/203" },
  { id: 4, name: "Mew ex", category: "singles", price: 349, currency: "MXN", status: "available", image_url: "", description: "Ligera, poderosa y lista para tu deck.", is_holo: true, set_name: "151", card_number: "151/165" },
  { id: 5, name: "Gengar V", category: "singles", price: 179, currency: "MXN", status: "available", image_url: "", description: "El favorito fantasma en una carta llena de actitud.", is_holo: false, set_name: "Golpe Fusión", card_number: "156/264" },
  { id: 6, name: "Eevee — Ilustración Rara", category: "singles", price: 479, currency: "MXN", status: "coming_soon", image_url: "", description: "Una ilustración tierna para fans de todas sus evoluciones.", is_holo: true, set_name: "Mascarada Crepuscular", card_number: "188/167" },
  { id: 7, name: "Booster Box — Destinos de Paldea", category: "sealed", price: 3199, currency: "MXN", status: "available", image_url: "", description: "36 sobres sellados para abrir, jugar y coleccionar.", is_holo: false, set_name: "Destinos de Paldea", card_number: "BOX-36" },
  { id: 8, name: "Elite Trainer Box — 151", category: "sealed", price: 1899, currency: "MXN", status: "sold_out", image_url: "", description: "Todo lo necesario para iniciar una aventura en Kanto.", is_holo: false, set_name: "151", card_number: "ETB-151" },
  { id: 9, name: "Booster Bundle — Fuerzas Temporales", category: "sealed", price: 649, currency: "MXN", status: "available", image_url: "", description: "Seis sobres, cero relleno y muchas posibilidades.", is_holo: false, set_name: "Fuerzas Temporales", card_number: "BB-06" },
  { id: 10, name: "Tin de Colección — Koraidon", category: "sealed", price: 549, currency: "MXN", status: "available", image_url: "", description: "Lata coleccionable con carta promo y sobres oficiales.", is_holo: true, set_name: "Escarlata y Violeta", card_number: "TIN-K01" },
  { id: 11, name: "Colección Premium — Charizard ex", category: "sealed", price: 1599, currency: "MXN", status: "coming_soon", image_url: "", description: "Promos, accesorios y sobres en una caja de exhibición.", is_holo: true, set_name: "Colección Premium", card_number: "PC-CHX" },
  { id: 12, name: "Blíster Triple — Viajes Unidos", category: "sealed", price: 329, currency: "MXN", status: "available", image_url: "", description: "Tres sobres y una carta promo exclusiva.", is_holo: false, set_name: "Viajes Unidos", card_number: "BL-03" },
  { id: 13, name: "Kit de Entrenador — Rivales Destinados", category: "collection", price: 999, currency: "MXN", status: "coming_soon", image_url: "", description: "Primera ola de la nueva colección. Aparta tu lugar.", is_holo: true, set_name: "Rivales Destinados", card_number: "KIT-01" },
  { id: 14, name: "Mini Tin — Evoluciones Prismáticas", category: "collection", price: 299, currency: "MXN", status: "available", image_url: "", description: "Formato compacto con arte conectable de colección.", is_holo: true, set_name: "Evoluciones Prismáticas", card_number: "MT-05" },
  { id: 15, name: "Poster Collection — 151", category: "collection", price: 729, currency: "MXN", status: "available", image_url: "", description: "Tres promos, sobres y un póster para celebrar Kanto.", is_holo: false, set_name: "151", card_number: "POSTER-01" },
  { id: 16, name: "Caja de Entrenador — Chispas Fulgurantes", category: "collection", price: 1399, currency: "MXN", status: "available", image_url: "", description: "Accesorios de juego, sobres y una caja lista para guardar.", is_holo: true, set_name: "Chispas Fulgurantes", card_number: "ETB-CF" },
  { id: 17, name: "Pokémon Center ETB — Destinos", category: "collection", price: 109, currency: "USD", status: "sold_out", image_url: "", description: "Edición especial importada para coleccionistas exigentes.", is_holo: true, set_name: "Destinos de Paldea", card_number: "PC-ETB" },
  { id: 18, name: "Álbum 9 Bolsillos — Energía", category: "collection", price: 449, currency: "MXN", status: "available", image_url: "", description: "Protege hasta 360 cartas con estilo eléctrico.", is_holo: false, set_name: "Accesorios TCG", card_number: "ALB-360" }
];
